spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drinklab
    username: postgres
    password: 12345
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
#  flyway:
#    locations:
#      - classpath:db/migration
#      - classpath:db/seed
security:
  jwt:
    secret: ef49705ba523370d9e2e1f633080dd4f
    expiration: 86400000 # 1 dia em milliseconds

drinklab:
  user:
    group:
      master: MASTER
      admin: ADMIN
#logging:
#  level:
#    root: "debug"